# Generated by Django 2.2 on 2019-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('number_of_methods', models.IntegerField()),
                ('number_of_properties', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DMathOperation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type_of_argument', models.CharField(max_length=50)),
                ('type_of_value', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('min_value', models.CharField(max_length=50)),
                ('max_value', models.CharField(max_length=50)),
                ('format_of_value', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
