# Generated by Django 2.2 on 2019-04-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pascal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dclass',
            old_name='number_of_methods',
            new_name='num_of_methods',
        ),
        migrations.RenameField(
            model_name='dclass',
            old_name='number_of_properties',
            new_name='num_of_properties',
        ),
    ]
