# Generated by Django 2.2 on 2019-04-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pascal', '0002_auto_20190407_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dclass',
            old_name='num_of_properties',
            new_name='num_of_fields',
        ),
    ]
