# Generated by Django 2.2 on 2019-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascal', '0003_auto_20190407_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dclass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dmathoperation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
